// Regenerate the typed client from cards/<service-id>/openapi.json (written by `uv run akashi-schemas`).
//   pnpm --filter @akashi/api-client generate
// Writes src/generated/{cite,code,now}.ts (openapi-typescript) and src/generated/routes.ts: the method + path
// allowlist per service that the web proxies check before forwarding anything.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const cards = join(here, "../../../cards");
const out = join(here, "../src/generated");
const SERVICES = { cite: "citation-verify", code: "code-reality-check", now: "live-facts" };

const routes = {};
for (const [key, id] of Object.entries(SERVICES)) {
  const spec = join(cards, id, "openapi.json");
  execFileSync("openapi-typescript", [spec, "-o", join(out, `${key}.ts`)], { stdio: "inherit" });
  const { paths } = JSON.parse(readFileSync(spec, "utf8"));
  routes[id] = Object.entries(paths).flatMap(([path, ops]) => Object.keys(ops).map((m) => `${m.toUpperCase()} ${path}`));
}

const body = `// Generated by scripts/generate.mjs from cards/*/openapi.json. Do not edit.
export const SERVICE_ROUTES = ${JSON.stringify(routes, null, 2)} as const;

export type ServiceId = keyof typeof SERVICE_ROUTES;
export type ServiceRoute<S extends ServiceId> = (typeof SERVICE_ROUTES)[S][number];
`;
writeFileSync(join(out, "routes.ts"), body);
console.log(`routes: ${Object.entries(routes).map(([id, r]) => `${id} ${r.length}`).join(", ")}`);
