// Fetch each catalog provider's icon once into public/logos/<id>.png and regenerate src/lib/constants/logos.ts.
// Usage: AKASHI_API_URL=http://localhost:8000 node scripts/fetch-logos.mjs
// Icons are the providers' own favicons (nominative use, to identify the integration), via Google's s2 service.
import { writeFile } from "node:fs/promises";

const API = process.env.AKASHI_API_URL ?? "http://localhost:8000";
const SIZE = 128;
const MIN_BYTES = 200; // s2 answers a generic 16px globe for unknown domains; real icons are larger
const SKIP = new Set(["akashi"]); // drawn with the 証 seal instead

const catalog = await (await fetch(`${API}/v1/catalog`)).json();
const saved = [];
for (const p of catalog.providers) {
  if (SKIP.has(p.id)) continue;
  const url = `https://www.google.com/s2/favicons?domain=${encodeURIComponent(p.logoDomain)}&sz=${SIZE}`;
  const res = await fetch(url);
  const bytes = Buffer.from(await res.arrayBuffer());
  if (!res.ok || bytes.length < MIN_BYTES) {
    console.log(`skip ${p.id} (${p.logoDomain}): ${res.status} ${bytes.length}B`);
    continue;
  }
  await writeFile(`public/logos/${p.id}.png`, bytes);
  saved.push(p.id);
  console.log(`ok   ${p.id} ${bytes.length}B`);
}
const body = `/** Provider ids with a mark in public/logos/<id>.png (regenerated by scripts/fetch-logos.mjs). */
export const LOGO_IDS: ReadonlySet<string> = new Set<string>(${JSON.stringify(saved.sort())});
`;
await writeFile("src/lib/constants/logos.ts", body);
console.log(`${saved.length} logos`);
