/** Provider ids with a mark in public/logos/<id>.png (regenerated by scripts/fetch-logos.mjs). */
export const LOGO_IDS: ReadonlySet<string> = new Set<string>(["depsdev","firecrawl","github","groq","ipinfo","jina","npm","openweather","pypi","serper","wayback","wikidata","wikipedia","youtube"]);
